### ISSUE TITLE
1-19-5e5 Kernel compatibility with EasyMint, checkdisk issue

### ISSUE THREAD

**Issue by mzryz** [freemint/freemint.github.io#1]
Hey guys,

I am using EasyMint and had to update to the latest kernel/xaaes for my 030 TT 1-19-5e5. When I updated, it always seems to think my LNX partition wasn't cleanly unmounted previously and does a check, it does this every time. This seems to have happened since I did those updates, the rest of the system works ok. Can anyone make any suggestions rather than me disabling the disk check alltogether?

This is the log on boot:
pid 4 (sh) Ext2-FS [E]: WARNING mounting unchecked fs, running e2fsck is recommended
sid: PANIC: Cannot open pipe (-> -33)
pid 2 (sid): WARNING: thread 'sid' (2) exits with status 1

Then it proceeds to check.

Thx

**Comment by mikrosk** [comment]
Hi @mzryz, please report it in https://github.com/freemint/freemint/issues as this is just a website's repository. :)

Anyway it's very strange, this issue has been fixed a long time ago. Maybe you didn't update your kernel modules, too?
